name = "Lax253009"
defaultTargets = ["Lax253009"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax434930"
git = "https://github.com/EdouardBonnet/classical-complexity"
rev = "0c0840319318215fd7b36a9a822b81ce55cf6941"
subDir = "concepts"

[[lean_lib]]
name = "Lax253009"

[[require]]
name = "Lax666725"
git = "https://github.com/EdouardBonnet/randomized-complexity"
rev = "31864d7e719d388b3d682a807fa2e56c8f9e0ae6"
subDir = "concepts"
